management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  data:
    redis:
      port: 6379
      host: redis
      timeout: 10000
  jpa:
    hibernate:
      ddlAuto: update
      formatSql: true
    showSql: true
  datasource:
    url: jdbc:postgresql://db:5432/headlight-website
    username: porunit
    password: 358000
  flyway:
    enabled: false




